# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('sort_order', models.IntegerField()),
                ('ship', models.CharField(max_length=25)),
                ('image_link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('wieght', models.FloatField()),
                ('capacity', models.IntegerField()),
                ('year', models.IntegerField()),
                ('description', models.CharField(default='', max_length=250)),
            ],
        ),
    ]
