# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deck_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='ship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deck_service.Ship'),
        ),
    ]
