# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck_service', '0002_auto_20160209_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='image_link',
            field=models.CharField(default='http://image.com', max_length=255),
        ),
    ]
